### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by grostedo** [Nathancrz/MTB-telemetry#1]
Hi, I am Grostedo.  I was working on your project for my motorcycle, but then I noticed that there were multiple errors in the code. Can you please help me fixing it? Thank you, have a good day.

**Comment by nathancrz** [comment]
Hello, i will have very limited time until august but i am very glad my
work inspired you. I have new codes I didn’t push on GitHub but I think
that the errors will still be there so tell me what are the problems on
your side, I’ll try to fix them.

**Comment by nathancrz** [comment]
Hi, i uploaded the latest versions of the code, both the GUI i made with customtkinter and the basic python script. Hope this helps :)

**Comment by grostedo** [comment]
Everything solved, thank you!
